name: openvidu-application

services:
  openvidu-server:
    build: .
    container_name: openvidu-server
    restart: unless-stopped
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=MY_SECRET
      - HTTPS_PORT=4443
    networks:
      - openvidu-network

networks:
  openvidu-network:
    name: openvidu-network
    driver: bridge