services:
  kurento-media-server:
    platform: linux/amd64  # 애플실리콘 이슈
    image: kurento/kurento-media-server:latest
    container_name: kurento-media-server
    restart: always
    ports:
      - "8888:8888"
      - "5000-5100:5000-5100/udp"
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5100
    networks:
      - kurento-network

networks:
  kurento-network:
    name: kurento-network
    driver: bridge