version: '3.8'

services:
  kurento-media-server:
    platform: linux/amd64  # 애플실리콘 이슈
    image: kurento/kurento-media-server:latest
    container_name: kurento-media-server
    restart: always
    ports:
      - "8888:8888"
      - "5000-5050:5000-5050/udp"
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
      - KMS_STUN_IP=121.131.148.39          # Coturn 서버의 외부 IP
      - KMS_STUN_PORT=3478                 # Coturn 서버의 포트
      - KMS_TURN_URL=testuser:testpassword@121.131.148.39:3478?transport=udp
    networks:
      - kurento-network

networks:
  kurento-network:
    name: kurento-network
    driver: bridge